// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN1P0NLfTGqkAXFs5YVAfvtQvbI5O8EXQ',
    appId: '1:659543497868:web:572820d85f575bb02eafa9',
    messagingSenderId: '659543497868',
    projectId: 'ewalletapp2',
    authDomain: 'ewalletapp2.firebaseapp.com',
    storageBucket: 'ewalletapp2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBohiWebYYRqS-RcYQ2m-4iIkTJZLUQpE',
    appId: '1:659543497868:android:962ac485af44a8962eafa9',
    messagingSenderId: '659543497868',
    projectId: 'ewalletapp2',
    storageBucket: 'ewalletapp2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5b2Npb5rb8MhWwQ1nhS_ERSw11vqhrrc',
    appId: '1:659543497868:ios:f7db32d0f187bbe12eafa9',
    messagingSenderId: '659543497868',
    projectId: 'ewalletapp2',
    storageBucket: 'ewalletapp2.appspot.com',
    iosBundleId: 'com.example.ewalletapp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5b2Npb5rb8MhWwQ1nhS_ERSw11vqhrrc',
    appId: '1:659543497868:ios:f7db32d0f187bbe12eafa9',
    messagingSenderId: '659543497868',
    projectId: 'ewalletapp2',
    storageBucket: 'ewalletapp2.appspot.com',
    iosBundleId: 'com.example.ewalletapp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN1P0NLfTGqkAXFs5YVAfvtQvbI5O8EXQ',
    appId: '1:659543497868:web:a30838e73bdb89ac2eafa9',
    messagingSenderId: '659543497868',
    projectId: 'ewalletapp2',
    authDomain: 'ewalletapp2.firebaseapp.com',
    storageBucket: 'ewalletapp2.appspot.com',
  );
}
