// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJt4B9ckP0UA2W-dPu6gUQmKYhU6sEeEo',
    appId: '1:26632030962:web:c91b64011438fb98d9de6b',
    messagingSenderId: '26632030962',
    projectId: 'bncc-flutter-project',
    authDomain: 'bncc-flutter-project.firebaseapp.com',
    storageBucket: 'bncc-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzd1HicwbT9wP28IuJIFVyYhFv6m8gJTg',
    appId: '1:26632030962:android:c3ace0cdf28712e4d9de6b',
    messagingSenderId: '26632030962',
    projectId: 'bncc-flutter-project',
    storageBucket: 'bncc-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD65s4JKHwzEgG5OWy1I-5zvwSPxf1r59w',
    appId: '1:26632030962:ios:c88dd29350791abfd9de6b',
    messagingSenderId: '26632030962',
    projectId: 'bncc-flutter-project',
    storageBucket: 'bncc-flutter-project.appspot.com',
    iosBundleId: 'com.example.ewalletapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD65s4JKHwzEgG5OWy1I-5zvwSPxf1r59w',
    appId: '1:26632030962:ios:c88dd29350791abfd9de6b',
    messagingSenderId: '26632030962',
    projectId: 'bncc-flutter-project',
    storageBucket: 'bncc-flutter-project.appspot.com',
    iosBundleId: 'com.example.ewalletapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJt4B9ckP0UA2W-dPu6gUQmKYhU6sEeEo',
    appId: '1:26632030962:web:adba2f431ce8b895d9de6b',
    messagingSenderId: '26632030962',
    projectId: 'bncc-flutter-project',
    authDomain: 'bncc-flutter-project.firebaseapp.com',
    storageBucket: 'bncc-flutter-project.appspot.com',
  );
}
